In [1]:
import numpy as np
from mis_utils import *

In [2]:
nn = np.array([[0,1,1],[1,0,0],[0,1,0]])
na = nn2na(nn, node_names = np.array(('1', '2', '3')), show_results = True)

[[0 1]
 [0 2]
 [1 0]
 [2 1]]
Input: 
 [[0 1 1]
 [1 0 0]
 [0 1 0]]

Column names: 12-13-21-32

Output: 
 [[ 1  1 -1  0]
 [-1  0  1 -1]
 [ 0 -1  0  1]]



In [3]:
nn1 = np.array([[0,1,1],[0,0,0],[0,0,0]])
na1 = nn2na(nn1,  show_results = True)

[[0 1]
 [0 2]]
Input: 
 [[0 1 1]
 [0 0 0]
 [0 0 0]]

Column names: 12-13

Output: 
 [[ 1  1]
 [-1  0]
 [ 0 -1]]



In [4]:
NN = np.array([[0, 1, 1, 0, 0, 0],
               [0, 0, 0, 1, 0, 1],
               [0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 1],
               [0, 0, 0, 0, 0, 0]])

In [5]:
result, arcs = nn2na(NN, show_results=True)

[[0 1]
 [0 2]
 [1 3]
 [1 5]
 [2 4]
 [3 5]
 [4 5]]
Input: 
 [[0 1 1 0 0 0]
 [0 0 0 1 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]]

Column names: 12-13-24-26-35-46-56

Output: 
 [[ 1  1  0  0  0  0  0]
 [-1  0  1  1  0  0  0]
 [ 0 -1  0  0  1  0  0]
 [ 0  0 -1  0  0  1  0]
 [ 0  0  0  0 -1  0  1]
 [ 0  0  0 -1  0 -1 -1]]

